language: node_js
node_js:
  - "stable"
cache: npm
on:
  branch:
    - master
jobs:
  include:
    - stage: Install dependencies
      script:
        - npm install
    - stage: Run tests
      script:
        - npm test