name: Test
on:
  push:
   branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Run tests
      run: ($env:CI = "true") -and (npm test)